version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-alpine
    container_name: pinegap-rabbitmq
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error}]
    ports:
      - "15672:15672"
      - "5672:5672"

  db:
    image: postgres:11-alpine
    container_name: pinegap-database
    environment:
      - POSTGRES_DB=pinegap_db
      - POSTGRES_USER=PINEGAP_DB_USER
      - POSTGRES_PASSWORD=PINEGAP_DB_PASSWD_TO_CHANGE
    ports:
      - "5432:5432"
    volumes:
      - ./dump_2024-08-28_14_26_17.sql:/docker-entrypoint-initdb.d/dump_2024-08-28_14_26_17.sql

  web:
    container_name: pinegap-django
    build: .
    image: pinegap/pinegap-manager:latest
    environment:
      - DB_PORT_5432_TCP_HOST=db
      - DEBUG=True
      - RABBIT_PORT_5672_TCP=rabbitmq:5672
      - DJANGO_SETTINGS_MODULE=app.settings
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8003:8003"
    links:
      - db
      - rabbitmq

  nginx-api:
    image: nginx:latest
    container_name: pinegap-nginx
    ports:
      - "8083:8083"
    volumes:
      - ./nginx_docker.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  pinegap-flutter:
    build:
      context: /home/ubuntu/pinegap-flutter
      dockerfile: Dockerfile
    container_name: pinegap-flutter
    ports:
      - "80:80"
    depends_on:
      - web